"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[╭─](white) $os $directory $git_state $git_branch $git_status $fill $cmd_duration $time
[╰─](white)$character
'''

command_timeout = 1000

palette = 'catppuccin_mocha'

[os]
disabled = false

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "sapphire"
before_repo_root_style = "blue dimmed"
repo_root_style = "blue bold"
repo_root_format = '[  ]($style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
truncation_length = 0
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "green"
format = 'on [$symbol $branch(:$remote_branch)]($style)'

[git_status]
style = "sky"
format = '[($all_status$ahead_behind )]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)]($style)'
modified = '[$count]($style)'
disabled = false

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_metrics]
format = '([++$added]($added_style) )([--$deleted]($deleted_style) )'
disabled = false
added_style = 'green'
deleted_style = 'red'

[nodejs]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[c]
symbol = " "
style = "green"
format = '[$symbol]($style)'

[rust]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[golang]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[php]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[java]
symbol = " "
style = "green"
format = '[$symbol]($style)'

[kotlin]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[haskell]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[python]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[docker_context]
symbol = ""
style = "green"
format = '[$symbol]($style)'

[conda]
symbol = "  "
style = "green"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "lavender"
format = '[ at  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " $duration "
disabled = false
show_notifications = true
min_time_to_notify = 45000

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[fill]
symbol = '─'
style = 'white'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
