# Package Configuration for Multi-Platform Setup
# This file defines packages to install on different platforms using reusable sections

# ===============================================================================
# COMMON TOOL DEFINITIONS
# ===============================================================================

[common_tools]
# Terminal tools available across all platforms (macOS, Fedora, Debian, Android)
terminal = [
    "htop",
    "btop",
    "tealdeer",
    "git",
    "wget",
    "curl",
    "zsh",
    "vim",
    "neovim",
    "bat",
    "direnv",
    "fastfetch",
    "fzf",
    "git-delta",
    "jq",
    "pipx",
    "ripgrep",
    "tar",
    "tmux",
    "tree",
    "xclip",
    "zoxide",
    "croc",
    "openssh",
    "atuin",
    "topgrade",
    "starship",
    "gh",
    "coreutils",
    "binutils",
    "protobuf",
    "nextdns",
    "gcc",
    "node",
    "python",
    "rustup",
    "sqlite",
    "ollama",
    "llvm",
    "ffmpeg",
    "parallel",
    "redis",
    "docker",
    "kubectl",
    "uv",
    "grpc",
    "stow",
]

# Development tools that may have different package names
languages = ["gcc", "node", "python", "rustup", "sqlite"]

# ===============================================================================
# PLATFORM CONFIGURATIONS
# ===============================================================================

[platforms.macos]
[platforms.macos.terminal_tools]
# macOS uses Homebrew for all terminal tools (common tools + macOS specific)
# Common tools will be automatically added by the setup script from common_tools.terminal
homebrew = ["gnu-sed", "openjdk"] # Only macOS-specific tools

[platforms.macos.gui_apps]
casks = [
    "alt-tab",
    "android-studio",
    "bitwarden",
    "brave-browser@beta",
    "zen-browser",
    "localsend",
    "maccy",
    "obsidian",
    "rectangle",
    "signal@beta",
    "visual-studio-code",
    "zed@preview",
    "onlyoffice",
    "tailscale",
    "wezterm",
    "postman",
    "orbstack",
]

# ===============================================================================

[platforms.fedora]
[platforms.fedora.terminal_tools]
# Fedora uses DNF for all packages (common tools + Fedora specific)
# Common tools will be automatically added by the setup script from common_tools.terminal
dnf = [
    # Fedora specific tools only
    "java-latest-openjdk",
    "postgresql-server",
    "postgresql-devel",
    "code",
    "dnf-plugins-core",
    "btrfs-assistant",
    "lm_sensors",
    "pkg-config",
    "dpkg",
    "tailscale",
    "wezterm",
]

[platforms.fedora.gui_apps]
flatpak = [
    "app.zen_browser.zen",
    "com.brave.Browser",
    "dev.zed.Zed",
    "org.signal.Signal",
    "md.obsidian.Obsidian",
    "org.localsend.localsend_app",
    "com.bitwarden.desktop",
    "org.onlyoffice.desktopeditors",
    "com.obsproject.Studio",
    "org.mozilla.Thunderbird",
    "com.valvesoftware.Steam",
]

[platforms.fedora.bloatware_removal]
# KDE and default Fedora packages to remove
kde_packages = [
    "firefox",           # Default browser (we install Brave/Zen instead)
    "kmahjongg",         # KDE Mahjong game
    "kmines",            # KDE Minesweeper game
    "kpatience",         # KDE Solitaire game
    "akregator",         # RSS reader
    "kmail",             # Email client
    "neochat",           # Matrix chat client
    "kontact",           # PIM suite
    "korganizer",        # Calendar/organizer
    "okular",            # Document viewer
]

libreoffice_packages = [
    "libreoffice-draw",     # Drawing application
    "libreoffice-math",     # Formula editor
    "libreoffice-calc",     # Spreadsheet
    "libreoffice-writer",   # Word processor
    "libreoffice-core",     # Core LibreOffice
    "libreoffice-base",     # Database
    "libreoffice-impress",  # Presentations
]

pim_packages = [
    "sieve-editor",         # Email sieve editor
    "pim-data-exporter",    # PIM data export tool
]

# ===============================================================================

[platforms.debian]
[platforms.debian.terminal_tools]
# APT for system packages only (essential system tools)
apt = [
    "openssh-client",
    "build-essential",
    "software-properties-common",
    "apt-transport-https",
    "ca-certificates",
    "gnupg",
    "lsb-release",
]

# Homebrew for terminal tools (common tools will be automatically added from common_tools.terminal)
homebrew = [] # Common tools will be added automatically by setup script

# ===============================================================================

[platforms.android]
[platforms.android.terminal_tools]
# Android/Termux uses pkg for all packages (common tools + Android specific)
# Common tools will be automatically added by the setup script from common_tools.terminal
pkg = [
    # Android specific tools only
    "termux-api",
    "termux-tools",
    "tsu",
]

# ===============================================================================
# PACKAGE MANAGER CONFIGURATIONS
# ===============================================================================

[package_managers]

[package_managers.homebrew]
# Homebrew configuration (used by macOS and Debian)
tap_repos = ["nextdns/tap"]
update_before_install = true

[package_managers.fedora_copr]
# COPR repositories for Fedora
repos = [
    "atim/starship",
    "lilay/topgrade",
    "lukenukem/asus-linux",
    "wezfurlong/wezterm-nightly",
]

[package_managers.fedora_external]
# External repositories for Fedora
[[package_managers.fedora_external.repos]]
name = "nextdns"
url = "https://repo.nextdns.io/nextdns.repo"

[[package_managers.fedora_external.repos]]
name = "vscode"
key = "https://packages.microsoft.com/keys/microsoft.asc"
repo = """[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
autorefresh=1
type=rpm-md
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc"""

[[package_managers.fedora_external.repos]]
name = "tailscale"
url = "https://pkgs.tailscale.com/stable/fedora/tailscale.repo"


# ===============================================================================
# CONFIGURATION SECTIONS
# ===============================================================================

[system]
# System-level configuration
hostname = "pixw"

[git]
# Git configuration defaults
default_name = "PiX"
default_email = "69745008+pixincreate@users.noreply.github.com"

[logging]
# Logging configuration
log_file = "~/Dev/.configs/setup.log"

[directories]
# Directory paths and configurations
configs_path = "~/Dev/.configs"
fonts_source = "~/Dev/.configs/fonts"
wallpapers_dir = "~/Pictures/Wallpapers"
screenshots_dir = "~/Pictures/Screenshots"
gitconfig_local = "~/.config/gitconfig/.gitconfig.local"
ssh_dir = "~/.ssh"
ssh_key = "~/.ssh/id_ed25519"
ssh_signing_key = "~/.ssh/id_ed25519_sign.pub"
zsh_dir = "~/.zsh"
zshrc_file = "~/.zsh/.zshrc"
zsh_source = "~/Dev/.configs/home/zsh/.zsh/.zshrc"
additionals_zsh = "~/.zsh/.additionals.zsh"
rish_dir = "~/.rish"  # Android specific
zgenom_dir = "~/.zsh/.zgenom"
config_dir = "~/.config"
stow_packages = ["config", "git", "ssh", "vscode", "zsh", "wallpaper"]
stow_source = "~/Dev/.configs/home"

# Platform-specific font directories
[directories.fonts_target]
macos = "~/Library/Fonts"
fedora = "~/.local/share/fonts"
debian = "~/.local/share/fonts"
android = "~/.local/share/fonts"

# ===============================================================================
# PACKAGE MAPPING
# ===============================================================================
# This section helps map common package names to platform-specific names

[package_mapping]
# Package name mappings for different platforms
[package_mapping.python]
macos = "python"
fedora = "python3"
debian = "python3"
android = "python"

[package_mapping.openssh]
macos = "openssh"
fedora = "openssh"
debian = "openssh-client"
android = "openssh"

[package_mapping.pipx]
macos = "pipx"
fedora = "pipx"
debian = "pipx"
android = "python" # Install via pip
